- op: replace
  path: /spec/template/spec/containers/0/livenessProbe/httpGet/path
  value: /healthz
- op: replace
  path: /spec/template/spec/containers/0/readinessProbe/httpGet/path
  value: /healthz
