apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: archmeister
    path: deployment_patch.yaml
resources:
  - _manifest.yaml
