apiVersion: v1
clusters:
- cluster:
    server: https://<x>-vcluster.dev.acmeco.io
    insecure-skip-tls-verify: true
  name: <x>-vcluster
contexts:
- context:
    cluster: <x>-vcluster
    namespace: acmeco
    user: <x>-vcluster-admin
  name: vcluster_<x>_acmeco_k2
current-context: vcluster_<x>_acmeco_k2
kind: Config
preferences: {}
users:
- name: <x>-vcluster-admin
  user:
    token: placeholder

