storage:
  persistence: false
fallbackHostDns: true
multiNamespaceMode:
  enabled: true
mapServices:
  fromHost:
  - from: acmeco/redis-master
    to: acmeco/redis-master
  - from: acmeco/rabbitmq
    to: acmeco/rabbitmq
coredns:
  image: coredns/coredns:1.10.1
sync:
  secrets:
    all: true
  configmaps:
    all: true
  ingresses:
    enabled: true
  generic:
    clusterRole:
      extraRules:
        - apiGroups: [ "apiextensions.k8s.io" ]
          resources: [ "customresourcedefinitions" ]
          verbs: [ "get", "list", "watch" ]
    role:
      extraRules:
        - apiGroups: ["jaegertracing.io"]
          resources: ["jaegers"]
          verbs: ["get", "list", "watch"]
        - apiGroups: ["postgresql.cnpg.io"]
          resources: ["backups", "clusters", "poolers", "scheduledbackups" ]
          verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
    config: |-
      version: v1beta1
      import:
      - kind: Jaeger
        apiVersion: jaegertracing.io/v1